name: Deploy to VPS
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          cd backend/
          pip3 install -r requirements.txt
      - name: SSH into server and deploy
        uses: LuisEnMarroquin/setup-ssh-action@v2.0.0
        with:
          ORIGIN: ${{ secrets.VPS_HOST }}
          USER: ${{ secrets.VPS_USER }}
          SSHKEY: ${{ secrets.SSH_PRIVATE_KEY }}
          PORT: 22
          NAME: production
        run: |
            ssh production ls --help
            cd /home/web/k-playlist/backend/
            . start.sh
